const MILLISECONDS_PER_DAY = 24 * 60 * 60 * 1000
const MILLISECONDS_PER_HOUR = 60 * 60 * 1000
const TASK_CALENDAR_ID = ""
const PENDING_TASK_PREFIX = "[TASK][PENDIENTE]"
const DONE_TASK_PREFIX = "[TASK][COMPLETADA]"